# Generated by Django 5.2.3 on 2025-07-04 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('father_occupation', models.CharField(blank=True, max_length=100)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('present_address', models.TextField()),
                ('permanent_address', models.TextField(blank=True)),
                ('telephone_residence', models.CharField(blank=True, max_length=15)),
                ('telephone_mobile', models.CharField(max_length=15)),
                ('allergies', models.TextField(blank=True)),
                ('x_board', models.CharField(blank=True, max_length=100)),
                ('x_year', models.CharField(blank=True, max_length=10)),
                ('x_percent', models.CharField(blank=True, max_length=10)),
                ('xii_board', models.CharField(blank=True, max_length=100)),
                ('xii_year', models.CharField(blank=True, max_length=10)),
                ('xii_percent', models.CharField(blank=True, max_length=10)),
                ('btech1_sem1', models.CharField(blank=True, max_length=10)),
                ('btech1_sem2', models.CharField(blank=True, max_length=10)),
                ('btech2_sem3', models.CharField(blank=True, max_length=10)),
                ('btech2_sem4', models.CharField(blank=True, max_length=10)),
                ('btech3_sem5', models.CharField(blank=True, max_length=10)),
                ('btech3_sem6', models.CharField(blank=True, max_length=10)),
                ('btech4_sem7', models.CharField(blank=True, max_length=10)),
                ('btech4_sem8', models.CharField(blank=True, max_length=10)),
                ('mtech1_sem1', models.CharField(blank=True, max_length=10)),
                ('mtech1_sem2', models.CharField(blank=True, max_length=10)),
                ('mtech2_sem3', models.CharField(blank=True, max_length=10)),
                ('mtech2_sem4', models.CharField(blank=True, max_length=10)),
                ('course_name', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=20)),
                ('institute_name', models.CharField(max_length=200)),
                ('training_duration', models.CharField(max_length=50)),
                ('training_from', models.DateField()),
                ('training_to', models.DateField()),
                ('photograph', models.ImageField(upload_to='photographs/')),
                ('cv_upload', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('identification_doc', models.FileField(upload_to='ids/')),
                ('signature_upload', models.ImageField(upload_to='signatures/')),
                ('declaration_date', models.DateField()),
                ('photo_confirm', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('review_comments', models.TextField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
