# Generated by Django 5.2.3 on 2025-07-04 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role_based_reg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('employee_id', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('reporting_manager', models.CharField(max_length=100)),
                ('years_of_experience', models.CharField(max_length=20)),
                ('id_proof', models.FileField(upload_to='hr/id_proofs/')),
                ('authorization_letter', models.FileField(blank=True, null=True, upload_to='hr/auth_letters/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='role_based_reg.user')),
            ],
        ),
    ]
