# not using 3306 for port binding as mySQl already using it on my system so 3307 

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3307:3306"   
    environment:
      MYSQL_DATABASE: drdoc_db
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: testUser
      MYSQL_PASSWORD: test1234
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  web:
    build: .
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/application_portal
      - ./media:/application_portal/media
    depends_on:
      - db
    env_file:
      - .env

volumes:
  mysql_data:
