# Generated by Django 5.2.3 on 2025-07-05 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingapplication',
            old_name='cgpa',
            new_name='btech1_sem1',
        ),
        migrations.RenameField(
            model_name='trainingapplication',
            old_name='branch',
            new_name='father_name',
        ),
        migrations.RenameField(
            model_name='trainingapplication',
            old_name='mobile_phone',
            new_name='telephone_mobile',
        ),
        migrations.RemoveField(
            model_name='trainingapplication',
            name='bonafide_certificate',
        ),
        migrations.RemoveField(
            model_name='trainingapplication',
            name='marksheet',
        ),
        migrations.AddField(
            model_name='trainingapplication',
            name='allergies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trainingapplication',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingapplication',
            name='btech1_sem2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingapplication',
            name='btech2_sem3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingapplication',
            name='btech2_sem4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingapplication',
            name='btech3_sem5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingapplication',
            name='btech3_sem6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingapplication',
            name='btech4_sem7',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingapplication',
            name='btech4_sem8',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingapplication',
            name='declaration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingapplication',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingapplication',
            name='father_occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='trainingapplication',
            name='mtech1_sem1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingapplication',
            name='mtech1_sem2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingapplication',
            name='mtech2_sem3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingapplication',
            name='mtech2_sem4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingapplication',
            name='permanent_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trainingapplication',
            name='photograph',
            field=models.FileField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='trainingapplication',
            name='present_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trainingapplication',
            name='signature_upload',
            field=models.FileField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='trainingapplication',
            name='telephone_residence',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='trainingapplication',
            name='x_board',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='trainingapplication',
            name='x_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingapplication',
            name='x_year',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='trainingapplication',
            name='xii_board',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='trainingapplication',
            name='xii_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingapplication',
            name='xii_year',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
